I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/labels/start.rpy", line 16, in script
    kioko """
Exception: Sayer 'kioko' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/labels/start.rpy", line 16, in script
    kioko """
  File "C:\Users\Jorman Fernandez\Documents\renpy projects\renpy-7.1.3-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jorman Fernandez\Documents\renpy projects\renpy-7.1.3-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'kioko' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Dr Purple 0.1
Sat Aug 24 16:02:20 2019
